### PR TITLE
Obtain C# project targets from project.assets.json

### LINKED ISSUE #23: AssemblyName ignored when referencing .csproj project
The language server seems to ignore the `AssemblyName` of referenced `.csproj` files, failing to reference the assembly when the name differs from the project filename. I found this out while trying to reference third-party projects that have multiple `.csproj` as they transition to netstandard and the new project format.

I'm using the latest version published for VS Code.

Minimal repro:

1. `dotnet new classlib -n Foo` (this is a C# project)
2. Add to `Foo.csproj` an `AssemblyName` property different than `Foo`, e.g. `Different`
3. `dotnet new classlib -n Bar -lang F#`
4. `dotnet add Bar reference Foo`
5. Open the namespace `Foo` in `Bar/Library.fs`
6. Build Bar

Both Foo and Bar will build successfully, but the language server will try to reference `Foo.dll` instead of `Different.dll` and fail.

### PR DESCRIPTION
**Pull request by mistiara**
Fixes #23. For C# project references, this composes the target DLL name from `project.assets.json` when it exists. Tell me if there's anything that I've missed or that you want me to change.

### CODE REVIEW

File: src/ProjectCracker/ProjectCracker.fs [hunk 1]
```diff
@@ -347,6 +351,7 @@ let private projectTarget(csproj: FileInfo) =
     let projectAssetsJson = FileInfo(Path.Combine [|csproj.DirectoryName; "obj"; "project.assets.json"|])
     if projectAssetsJson.Exists then 
         let assets = parseProjectAssets(projectAssetsJson)
+        let dllName = assets.projectName + ".dll"
```
Comment (mistiara) [inline src/ProjectCracker/ProjectCracker.fs]: I'd like feedback specially on `projectTarget`. I did the minimum amount of changes I could overall, but I wonder if this function needs cleanup.

Comment (georgewfraser) [reply src/ProjectCracker/ProjectCracker.fs]: Hmm, I'm not really sure what you mean. There's an assumption in this function that the .dll is always in `{projectDir}/bin/debug/{framework}/{projectName}.dll`, and there's probably a bunch of other cases where this rule needs to be more complicated...not really sure that's "cleanup" though.

Comment (georgewfraser) [reply src/ProjectCracker/ProjectCracker.fs]: Oh I see, two dllNames

**Comment by georgewfraser** [comment]
This is great thanks! The two dllNames is fine, the first one is just a placeholder to make F# compiler service happy.
